Rethink xLayers's UX
xlayers/xlayers pull request #395
Opened 2020-11-20 00:02 UTC by ayshiff

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Closes #379 

This PR updates the current UX workflow.

This is still a work in progress because I need to do some **adjustments, refactoring and add some tests**.
I want to have your point of view on my implementation.

## What is the new behavior?

On the landing page, users can choose their framework they wanna generate code for.
On the code generation UI, we only show the selected framework with the possibility to switch to other frameworks.

### Landing Page 

<p align="center">
<img width="1425" alt="Landing Page" src="https://user-images.githubusercontent.com/32459935/99737548-cca31e00-2ac8-11eb-955e-edf77c71750c.png">
</p>

### Code generation

<p align="center">
<img width="924" alt="Code generation 1" src="https://user-images.githubusercontent.com/32459935/99737640-fb20f900-2ac8-11eb-8081-1d3751fc7553.png">
</p>
<p align="center">
<img width="924" alt="Code generation 2" src="https://user-images.githubusercontent.com/32459935/99737658-096f1500-2ac9-11eb-9915-596ef2b9a862.png">
</p>

## New workflow

<p align="center">
<img width="624" alt="New workflow" src="https://user-images.githubusercontent.com/32459935/99737810-59e67280-2ac9-11eb-8034-a9218bf89bed.gif" />
</p>

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2020-12-20 18:35 UTC, Jefiozie commented
Hi @anediaz would you review this PR?

2020-12-23 08:05 UTC, anediaz reviewed
LGTM

2021-01-17 14:18 UTC, anediaz commented
The code review is OK for me, @manekinekko & @Jefiozie, could you please take a look and give your approval so it can be merged?
I can't wait to see the new UX present in xlayers.dev :-)

2021-01-18 19:32 UTC, Jefiozie requested changes
I think we are almost there, some small comments that we need to handle before merging this one in. I love the improvements you've made to the UI! Thank you 🙏🏻

2021-01-18 19:32 UTC, Jefiozie commented on apps/xlayers/src/app/editor/code/editor-container/editor-container.component.ts
> +  public selectedFramework: UICodeGen = codeGenList[0];
```suggestion
  public selectedFramework: UICodeGen = frameworks[0];
```

2021-01-18 19:32 UTC, Jefiozie commented on apps/xlayers/src/app/editor/code/editor-container/editor-container.component.ts
> +  constructor(private codegen: CodeGenService, private readonly store: Store) {}
```suggestion
  constructor(private readonly codegen: CodeGenService, private readonly store: Store) {}
```

2021-01-18 19:32 UTC, Jefiozie commented on apps/xlayers/src/app/editor/code/editor-container/editor-container.component.ts
> +      if (codegen.kind) {
Could `kind` be null/ falsy? If that is the case wouldn't line 38  file also?

2021-01-18 19:32 UTC, Jefiozie commented on apps/xlayers/src/home/landing/landing.component.ts
> +    console.log(framework);
I think this line can be removed

2021-01-18 21:05 UTC, ayshiff commented
Thank you for your comments !

I have a comment to make about the `.svg` framework icons.
The different sizes of framework icons on the landing page confuses me a bit but I don't know if we should correct this in this PR.
The icons should be resized so that they have the same height. 
I'll let you tell me if it's something that needs to be fixed or not.

2021-01-18 21:31 UTC, anediaz commented
Good point! I agree with you!

I've looked to the different .svg files we have and effectively, some of them have a defined ``height``and ``width``.
It'd be quite simple and fast to remove them, in order they have all the same initial size.

I think it is worth fixing it :-)

2021-01-19 12:17 UTC, ayshiff commented
> Good point! I agree with you!
> 
> I've looked to the different .svg files we have and effectively, some of them have a defined `height`and `width`.
> It'd be quite simple and fast to remove them, in order they have all the same initial size.
> 
> I think it is worth fixing it :-)

The problem was a little more complicated than that.
Removing the `height` and `width` didn't change the problem as the issue comes from the dimensions of what's inside the svg (`<g>` or `<path>`)
I resized the icons using a tool and now they have similar dimensions 👍

2021-02-01 14:24 UTC, ayshiff commented
@anediaz @Jefiozie Does everything look good to you?

2021-02-01 19:07 UTC, Jefiozie approved these changes
LGTM

2021-02-18 12:09 UTC, manekinekko commented
Thank you so much @ayshiff for your contribution ❤️
After iterating over your PR, I made a few changes based on your design to the landing page.

@Jefiozie @anediaz let me know what you think before I merge these changes to main.

![image](https://user-images.githubusercontent.com/1699357/108354658-0976d200-71ea-11eb-9613-89e977864e5d.png)

2021-02-18 12:09 UTC, manekinekko approved these changes

2021-02-18 18:13 UTC, Jefiozie commented
Okay, I reallly like this 🤩

LGTM!!! 🎉

2021-02-19 08:50 UTC, anediaz commented
I love the design, I find it very original :tada: :star_struck: 
Good work !!!

2021-03-23 13:29 UTC, manekinekko commented
Awesome job @ayshiff. Your code was merged in c1adf5418715929d547c2132d0aeb3b2120c68bd. Congratulations!

2021-03-23 13:29 UTC, closed without merging